(****************************************************************************)
(*                           the diy toolsuite                              *)
(*                                                                          *)
(* Jade Alglave, University College London, UK.                             *)
(* Luc aranget, INRIA Paris-Rocquencourt, France.                          *)
(*                                                                          *)
(* Copyright 2012-present Institut National de Recherche en Informatique et *)
(* en Automatique and the authors. All rights reserved.                     *)
(*                                                                          *)
(* This software is governed by the CeCILL-B license under French law and   *)
(* abiding by the rules of distribution of free software. You can use,      *)
(* modify and/ or redistribute the software under the terms of the CeCILL-B *)
(* license as circulated by CEA, CNRS and INRIA at the following URL        *)
(* "http://www.cecill.info". We also give a copy in LICENSE.txt.            *)
(****************************************************************************)

type 'stset stats =
  { states : 'stset;
    cfail : int ;
    cands : int ;
(* NB: pos and neg are w.r.t. proposition *)
    pos : int ;
    neg : int ;
(* flagged executions *)
    flagged : int list Flag.Map.t ;
(* Too much loop unrolling *)
    cutoff : string option;
  }

type ('conc, 'sets, 'rels) execution =
  { concrete : 'conc;
    sets : 'sets;
    rels : 'rels;
  }

type ('exec, 'es, 'stats) t =
  { execs : 'exec list;
    event_structures : 'es list;
    stats : 'stats;
  }

let empty_stats empty_stset =
  { states = empty_stset; cfail=0; cands=0; pos=0; neg=0;
    flagged=Flag.Map.empty; cutoff=None; }

module type PrinterConfig = sig
  val show : PrettyConf.show
  val shortlegend : bool
  val showkind : bool
  val speedcheck : Speed.t
  val restrict : Restrict.t
  val outcomereads : bool
  val badexecs : bool
  val badflag : string option
  val verbose : int
  val candidates : bool
  module PC : PrettyConf.S
end

(* module type RunResult = sig *)
(*   module S : SemExtra.S *)
(**)
(*   type nonrec stats = (S.A.StateSet.t, S.loc_set) stats *)
(*   type nonrec execution = (S.concrete, S.set_pp Lazy.t, S.rel_pp Lazy.t) execution *)
(*   type nonrec test_result = (execution, S.event_structure, stats) t *)
(**)
(*   val result : t *)
(* end *)

(* module Printer (O : PrinterConfig) (S : SemExtra.S) = struct *)
(*   module A = S.A *)
(**)
(*   type nonrec stats = A.StateSet.t stats *)
(*   type nonrec execution = (S.concrete, S.set_pp Lazy.t, S.rel_pp Lazy.t) execution *)
(*   type nonrec t = (execution, S.event_structure, stats) t *)
(**)
(*   module C = S.Cons *)
(*   module T = Test_herd.Make (S.A) *)
(*   module PP = Pretty.Make (S) *)
(**)
(* (* Check condition *) *)
(*   let check_cond test c = *)
(*     let open ConstrGen in *)
(*     let cstr = T.find_our_constraint test in *)
(*     match cstr with *)
(*     | ExistsState _ -> c.pos > 0 *)
(*     | NotExistsState _-> c.pos = 0 *)
(*     | ForallStates _  -> c.neg = 0 *)
(**)
(*   let check_wit test c = *)
(*     let open ConstrGen in *)
(*     let cstr = T.find_our_constraint test in *)
(*     match cstr with *)
(*     | ForallStates _ *)
(*     | ExistsState _ -> c.pos,c.neg *)
(*     | NotExistsState _-> c.neg,c.pos *)
(**)
(*   let has_bad_execs c = *)
(*     Flag.Map.mem Flag.Undef c.flagged || *)
(*     (match O.badflag with *)
(*     | None -> false *)
(*     | Some f -> Flag.Map.mem (Flag.Flag f) c.flagged) *)
(**)
(*   let dump_exec_graph (model : Model.t) (test : T.result) (exec : execution) chan = *)
(*     let open Printf in *)
(*     let module PC = O.PC in *)
(*     let cstr = T.find_our_constraint test in *)
(*     let legend = *)
(*       let pp_flag = *)
(*         match O.show with *)
(*         | PrettyConf.ShowFlag f -> sprintf ", flag %s" f *)
(*         | _ -> "" in *)
(*       let name = Test_herd.readable_name test in *)
(*       let pp_model = sprintf "%s" (Model.pp model) in *)
(*       if O.shortlegend then name *)
(*       else if O.showkind then *)
(*         if PC.texmacros then *)
(*           sprintf *)
(*             "\\mylegendkind{%s}{%s}{%s}" *)
(*             name *)
(*             (C.dump_as_kind cstr) *)
(*             pp_model *)
(*         else *)
(*           sprintf "Test %s%s%s%s" *)
(*             name *)
(*             (sprintf ": %s" (C.dump_as_kind cstr)) *)
(*             (match pp_model with *)
(*             | "" -> "" *)
(*             | _ -> sprintf " (%s)" pp_model) *)
(*             pp_flag *)
(*       else begin *)
(*         if PC.texmacros then *)
(*           sprintf *)
(*             "\\mylegend{%s}{%s}" *)
(*             name *)
(*             pp_model *)
(*         else *)
(*           sprintf "Test %s%s%s" name *)
(*             (match pp_model with *)
(*             | "" -> "" *)
(*             | _ -> sprintf ", %s" pp_model) *)
(*             pp_flag *)
(*       end *)
(*     in *)
(*     PP.dump_legend chan test legend exec.concrete *)
(*           ~sets:(Lazy.force exec.sets) (Lazy.force exec.rels) *)
(**)
(*   let relevant_states (t : t) = *)
(*     let c = t.stats in *)
(*     let do_restrict (st,flts) = *)
(*       let st = *)
(*         A.rstate_filter *)
(*           (fun rloc -> *)
(*             let loc = ConstrGen.loc_of_rloc rloc in *)
(*             match loc with *)
(*             | A.Location_global _ -> true *)
(*             | A.Location_reg _ -> A.LocSet.mem loc c.reads) *)
(*           st in *)
(*           st,flts in *)
(*     A.StateSet.map do_restrict c.states *)
(**)
(*   let print_result ~start_time (test : T.result) (t : t) : unit = *)
(*     let open ConstrGen in *)
(*     let cstr = T.find_our_constraint test in *)
(*     let c = t.stats in *)
(**)
(*     let observation = *)
(*       match O.speedcheck with *)
(*       | Speed.False -> *)
(*           fun _test conc -> *)
(*             if conc.pos = 0 then "Never" *)
(*             else if conc.neg = 0 then "Always" *)
(*             else "Sometimes" *)
(*       | Speed.(True | Fast) -> ( *)
(*           fun test -> *)
(*             match test.Test_herd.cond with *)
(*             | ForallStates _ -> *)
(*                 fun conc -> *)
(*                   (* we have discarded all possible positive states. *) *)
(*                   assert (conc.pos = 0); *)
(*                   (* This means that we can't answer "Never", as we don't *)
(*                      know about the positive cases. *) *)
(*                   if conc.neg = 0 then "Always" else "Sometimes" *)
(*             | ExistsState _ | NotExistsState _ -> *)
(*                 fun conc -> *)
(*                   (* We have discarded all negative states. *) *)
(*                   assert (conc.neg = 0); *)
(*                   (* This means that we can't answer 'Always', as we dont' *)
(*                      know about the negative cases. *) *)
(*                   if conc.pos = 0 then "Never" else "Sometimes") *)
(*     in *)
(**)
(* (* Reduce final states, so as to show relevant locations only *) *)
(*     let finals = if O.outcomereads then relevant_states t else c.states in *)
(*     let nfinals = A.StateSet.cardinal finals in *)
(* (* Header *) *)
(*     let tname = test.Test_herd.name.Name.name in *)
(*     let is_bad = has_bad_execs c in *)
(*     if not O.badexecs &&  is_bad then () else begin *)
(*     let open Printf in *)
(* (* Now output *) *)
(*     printf "Test %s %s\n" tname (C.dump_as_kind cstr) ; *)
(* (**********) *)
(* (* States *) *)
(* (**********) *)
(* (* Location out printing *) *)
(*     let tr_out = OutMapping.info_to_tr  test.Test_herd.info in *)
(*     printf "States %i\n" nfinals ; *)
(*     A.StateSet.pp stdout "" *)
(*       (fun chan st -> *)
(*         fprintf chan "%s\n" *)
(*           (A.do_dump_final_state *)
(*              test.Test_herd.type_env test.Test_herd.ffaults *)
(*              tr_out st)) *)
(*       finals ; *)
(* (* Condition result *) *)
(*     let ok = check_cond test c in *)
(*     printf "%s%s\n" *)
(*       (if Misc.is_some c.cutoff then "Loop " else "") *)
(*       (if is_bad then "Undef" else if ok then "Ok" else "No") ; *)
(*     let pos,neg = check_wit test c in *)
(*     printf "Witnesses\n" ; *)
(*     printf "Positive: %i Negative: %i\n" pos neg ; *)
(*     begin if O.verbose > 0 then *)
(*       Flag.Map.iter *)
(*         (fun flag execs -> *)
(*           printf "Flag %s: %s \n" *)
(*             (Flag.pp flag) *)
(*             (List.fold_right *)
(*                (fun i s -> s ^ (if s="" then "" else ",") ^ sprintf "%i" i) *)
(*                execs "")) *)
(*       c.flagged *)
(*     else *)
(*        Flag.Map.iter *)
(*         (fun flag _ ->  printf "Flag %s\n" (Flag.pp flag)) *)
(*         c.flagged *)
(*     end ; *)
(*     printf "Condition %a\n" (C.do_dump_constraints tr_out) cstr ; *)
(*     printf "Observation %s %s %i %i\n%!" tname *)
(*       (observation test c) c.pos c.neg ; *)
(*     (* do_show () ; *) *)
(*     printf "Time %s %0.2f\n" tname (Sys.time () -. start_time) ; *)
(*     if O.candidates then *)
(*       printf "Candidates %s %i\n" tname (c.cfail+c.cands) ; *)
(* (* Auto info or Hash only*) *)
(*     List.iter *)
(*       (fun (k,v) -> *)
(*         if Misc.string_eq k "Hash" then *)
(*           printf "%s=%s\n" k v) *)
(*       test.Test_herd.info ; *)
(*     print_newline () ; *)
(*     begin *)
(*       match c.cutoff with *)
(*       | Some msg -> *)
(*           Warn.warn_always *)
(*             "%a: unrolling limit exceeded at %s, legal outcomes may be missing." *)
(*             Pos.pp_pos0   test.Test_herd.name.Name.file *)
(*             msg *)
(*       | None -> () *)
(*     end *)
(*   end *)
(**)
(* end *)
